def call(String whoUpdated, String repository, String fromBranch, String toBranch) {
    withCredentials([sshUserPrivateKey(credentialsId: 'github-ssh', keyFileVariable: 'SSH_KEY')]) {
        sh """
            rm -rf ${repository}
            export GIT_SSH_COMMAND='ssh -i $SSH_KEY -o StrictHostKeyChecking=no'
            git clone --branch ${toBranch} git@github.com:Runic-Studios/${repository}.git ${repository}

            git config --global user.email "runicrealms.mc@gmail.com"
            git config --global user.name "RunicRealmsGithub"

            cd ${repository}

            gh auth setup-git
            gh pr create --base ${toBranch} --head ${fromBranch} --title 'AUTOGENERATED: Promote latest ${whoUpdated} image/artifact to production' \
              --body 'This PR promotes the latest tested ${whoUpdated} build from dev to production. This was triggered because of a push to ${whoUpdated} on ref main.'
        """
    }
}